@host = http://localhost:8000/api

### 
GET {{host}}/presets

###
GET {{host}}/presets/1

###
POST {{host}}/presets
Content-Type: application/json

{
    "name": "Low Performance",
    "device": "fan",
    "settings": {
        "intensity": 20
    }
}